version: '3.8'

services:
  app:
    image: mern-songs-app
    environment:
      - MONGO_URI=mongodb+srv://daniel:1234@cluster0.klfdb.mongodb.net/songs?retryWrites=true&w=majority&appName=Cluster0
    ports:
      - "10000:10000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
